### ISSUE TITLE
全部发送给GPT之后会有一个报错

### ISSUE THREAD

**Issue by a186232641** [EmbraceAGI/AutoNetGen#1]
STDOUT/STDERR
/home/sandbox/.local/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm****

**Comment by yzfly** [comment]
openai sandbox 问题，不影响使用
